server:
  port: 8090

spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  application:
    name: netty-push-client
  aop:
    auto: true
    proxy-target-class: true

logging:
  level:
    ROOT: info
    com.sundy: debug
    org.springframework: info

netty:
  clientId: crawler_1
  server:
    host: localhost
    port: 9090
